### ISSUE TITLE
resend比例与rtt计算的问题请教

### ISSUE THREAD

**Issue by wangyoucao577** [dearplain/penet#1]
https://github.com/dearplain/penet/blob/248e6ca5ff4f1944bbdabae101e8615919c2ea51/penet.go#L126
1.2倍的`rtt`没收到`ack`就`resend`, 所以核心点就是通过尽快重传来提升有效性么？这样应该会产生大量的无效重传吧?  同时还有可能产生`resend`峰值?
基于此，算法的前提假设是，带宽是足够的(几乎不会产生拥塞)，信道上主要的问题是会有随机丢包？所以`TCP`的效率上不去。

https://github.com/dearplain/penet/blob/248e6ca5ff4f1944bbdabae101e8615919c2ea51/penet.go#L310
另外，目前`rtt`的计算就简单的计算了单个包，算出来的`rtt`值不会有很大的抖动么? 

多谢!

**Comment by dearplain** [comment]
超过rtt没回复，就是丢了，为啥叫无效重传。
不是无限。发送次数有限制。resend计入发送次数。
rtt可以简单平滑下，就是上面注销掉的// u.rtt = u.rtt*0.8 + float64(rtt)*0.2。

**Comment by wangyoucao577** [comment]
简单计算出来的`rtt`应该抖动很大，1.2倍应该很容易因为抖动导致。这种情况下的发出的重传，可能大概率并没有必要。
之前实测过无线网络情况下，即使如上平滑之后，`rtt`的抖动依然会很大。不过没太实测过这种有线网络，也许`rtt`非常稳定?

**Comment by dearplain** [comment]
如果考虑抖动大的网络，可以改为2*rtt，能覆盖大部分情况就ok。或者可以计算方差进行动态调整。超时时间主要影响延迟。

**Comment by dearplain** [comment]
调整了rtt相关代码，初步测试，resend日志几乎消失了。
